# Generated by Django 5.0.3 on 2024-04-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('biography', models.TextField(max_length=1500)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
