# Generated by Django 5.0.3 on 2024-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1', '0002_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
